version: "3"
volumes:
  proxy-cache:
services:
  proxy:
    image: nginx:stable-alpine
    volumes:
      - proxy-cache:/srv/nginx-cache/
      - ./proxy.template:/etc/nginx/templates/default.conf.template
    ports:
      - "8080:80"
    environment:
      - UPSTREAM=http://backend:8043/

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../config.yaml:/app/config.yaml
