version: "3"
services:
  go-webcam:
    restart: always
    image: koestler/go-webcam
    volumes:
      - ${PWD}/config.yaml:/config.yaml:ro
      # - ${PWD}/auth.passwd:/auth.passwd:ro
    ports:
      - "80:8043"